import type { Metadata } from 'next'
import './globals.css'
import { Header } from '@/widgets/header'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`antialiased w-svw overflow-x-hidden`}>
                <Header />
                <main className="flex flex-col min-h-screen">{children}</main>
            </body>
        </html>
    )
}
